Run jar

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -1,4 +1,4 @@
-name: Run Tests
+name: Java CI with Gradle
 
 on:
   push:
@@ -9,34 +9,35 @@ on:
       - main
 
 jobs:
-  test:
+  build:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
+      - uses: actions/checkout@v2
       - name: Set up JDK 11
-        uses: actions/setup-java@v3
+        uses: actions/setup-java@v2
         with:
-          distribution: 'temurin'
           java-version: '11'
-
-      - name: Cache Gradle dependencies
-        uses: actions/cache@v3
-        with:
-          path: |
-            ~/.gradle/caches
-            ~/.gradle/wrapper
-          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
-          restore-keys: |
-            ${{ runner.os }}-gradle-
-
-      - name: Make gradlew executable
+          distribution: 'adopt'
+      - name: Install Chrome
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y google-chrome-stable
+      - name: Grant execute permission for gradlew
         run: chmod +x gradlew
-
+      - name: Verify JAR file exists
+        run: |
+          if [ ! -f ./artifacts/app-card-delivery.jar ]; then
+            echo "JAR file not found!"
+            exit 1
+          fi
+      - name: Start SUT
+        run: java  -jar ./artifacts/app-card-delivery.jar > sut.log 2>&1 &
+      - name: Wait for SUT
+        run: sleep 10
+      - name: Print SUT logs
+        run: cat sut.log
       - name: Build with Gradle
-        run: ./gradlew build
-
-      - name: Run tests
-        run: ./gradlew test -Dselenide.headless=true
+        run: ./gradlew test --info
+      - name: Kill Java processes
+        run: pkill -f 'java'
